// Mocks generated by Mockito 5.4.6 from annotations
// in my_todo_app/test/todo_provider_with_mock_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;
import 'dart:typed_data' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:sqflite_common/sqlite_api.dart' as _i4;
import 'package:sqflite_common/src/database.dart' as _i3;
import 'package:sqflite_common/src/factory.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSqfliteDatabase_1 extends _i1.SmartFake
    implements _i3.SqfliteDatabase {
  _FakeSqfliteDatabase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_2 extends _i1.SmartFake implements _i4.Database {
  _FakeDatabase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryCursor_3 extends _i1.SmartFake implements _i4.QueryCursor {
  _FakeQueryCursor_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatch_4 extends _i1.SmartFake implements _i4.Batch {
  _FakeBatch_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SqfliteDatabaseFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockSqfliteDatabaseFactory extends _i1.Mock
    implements _i5.SqfliteDatabaseFactory {
  @override
  _i2.Future<T> wrapDatabaseException<T>(_i2.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#wrapDatabaseException, [action]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#wrapDatabaseException, [action]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#wrapDatabaseException, [action]),
                ),
            returnValueForMissingStub:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#wrapDatabaseException, [action]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#wrapDatabaseException, [action]),
                ),
          )
          as _i2.Future<T>);

  @override
  _i3.SqfliteDatabase newDatabase(
    _i3.SqfliteDatabaseOpenHelper? openHelper,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#newDatabase, [openHelper, path]),
            returnValue: _FakeSqfliteDatabase_1(
              this,
              Invocation.method(#newDatabase, [openHelper, path]),
            ),
            returnValueForMissingStub: _FakeSqfliteDatabase_1(
              this,
              Invocation.method(#newDatabase, [openHelper, path]),
            ),
          )
          as _i3.SqfliteDatabase);

  @override
  void removeDatabaseOpenHelper(String? path) => super.noSuchMethod(
    Invocation.method(#removeDatabaseOpenHelper, [path]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Future<_i4.Database> openDatabase(
    String? path, {
    _i4.OpenDatabaseOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#openDatabase, [path], {#options: options}),
            returnValue: _i2.Future<_i4.Database>.value(
              _FakeDatabase_2(
                this,
                Invocation.method(#openDatabase, [path], {#options: options}),
              ),
            ),
            returnValueForMissingStub: _i2.Future<_i4.Database>.value(
              _FakeDatabase_2(
                this,
                Invocation.method(#openDatabase, [path], {#options: options}),
              ),
            ),
          )
          as _i2.Future<_i4.Database>);

  @override
  _i2.Future<void> closeDatabase(_i3.SqfliteDatabase? database) =>
      (super.noSuchMethod(
            Invocation.method(#closeDatabase, [database]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> deleteDatabase(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDatabase, [path]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<bool> databaseExists(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#databaseExists, [path]),
            returnValue: _i2.Future<bool>.value(false),
            returnValueForMissingStub: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<String> getDatabasesPath() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabasesPath, []),
            returnValue: _i2.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getDatabasesPath, []),
              ),
            ),
            returnValueForMissingStub: _i2.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getDatabasesPath, []),
              ),
            ),
          )
          as _i2.Future<String>);

  @override
  _i2.Future<void> setDatabasesPath(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setDatabasesPath, [path]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> writeDatabaseBytes(String? path, _i7.Uint8List? bytes) =>
      (super.noSuchMethod(
            Invocation.method(#writeDatabaseBytes, [path, bytes]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<_i7.Uint8List> readDatabaseBytes(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#readDatabaseBytes, [path]),
            returnValue: _i2.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
            returnValueForMissingStub: _i2.Future<_i7.Uint8List>.value(
              _i7.Uint8List(0),
            ),
          )
          as _i2.Future<_i7.Uint8List>);

  @override
  _i2.Future<T> invokeMethod<T>(String? method, [Object? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#invokeMethod, [method, arguments]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#invokeMethod, [method, arguments]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#invokeMethod, [method, arguments]),
                ),
            returnValueForMissingStub:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#invokeMethod, [method, arguments]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#invokeMethod, [method, arguments]),
                ),
          )
          as _i2.Future<T>);
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i4.Database {
  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#path)),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  bool get isOpen =>
      (super.noSuchMethod(
            Invocation.getter(#isOpen),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Database get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeDatabase_2(this, Invocation.getter(#database)),
            returnValueForMissingStub: _FakeDatabase_2(
              this,
              Invocation.getter(#database),
            ),
          )
          as _i4.Database);

  @override
  _i2.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<T> transaction<T>(
    _i2.Future<T> Function(_i4.Transaction)? action, {
    bool? exclusive,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action], {#exclusive: exclusive}),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#exclusive: exclusive},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#exclusive: exclusive},
                  ),
                ),
            returnValueForMissingStub:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#exclusive: exclusive},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#exclusive: exclusive},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> readTransaction<T>(
    _i2.Future<T> Function(_i4.Transaction)? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readTransaction, [action]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#readTransaction, [action]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#readTransaction, [action]),
                ),
            returnValueForMissingStub:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#readTransaction, [action]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#readTransaction, [action]),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> devInvokeMethod<T>(String? method, [Object? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#devInvokeMethod, [method, arguments]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#devInvokeMethod, [method, arguments]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#devInvokeMethod, [method, arguments]),
                ),
            returnValueForMissingStub:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#devInvokeMethod, [method, arguments]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#devInvokeMethod, [method, arguments]),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> devInvokeSqlMethod<T>(
    String? method,
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#devInvokeSqlMethod, [method, sql, arguments]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#devInvokeSqlMethod, [
                      method,
                      sql,
                      arguments,
                    ]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#devInvokeSqlMethod, [
                    method,
                    sql,
                    arguments,
                  ]),
                ),
            returnValueForMissingStub:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#devInvokeSqlMethod, [
                      method,
                      sql,
                      arguments,
                    ]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#devInvokeSqlMethod, [
                    method,
                    sql,
                    arguments,
                  ]),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<void> execute(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [sql, arguments]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<int> rawInsert(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawInsert, [sql, arguments]),
            returnValue: _i2.Future<int>.value(0),
            returnValueForMissingStub: _i2.Future<int>.value(0),
          )
          as _i2.Future<int>);

  @override
  _i2.Future<int> insert(
    String? table,
    Map<String, Object?>? values, {
    String? nullColumnHack,
    _i4.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insert,
              [table, values],
              {
                #nullColumnHack: nullColumnHack,
                #conflictAlgorithm: conflictAlgorithm,
              },
            ),
            returnValue: _i2.Future<int>.value(0),
            returnValueForMissingStub: _i2.Future<int>.value(0),
          )
          as _i2.Future<int>);

  @override
  _i2.Future<List<Map<String, Object?>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #query,
              [table],
              {
                #distinct: distinct,
                #columns: columns,
                #where: where,
                #whereArgs: whereArgs,
                #groupBy: groupBy,
                #having: having,
                #orderBy: orderBy,
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i2.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
            returnValueForMissingStub:
                _i2.Future<List<Map<String, Object?>>>.value(
                  <Map<String, Object?>>[],
                ),
          )
          as _i2.Future<List<Map<String, Object?>>>);

  @override
  _i2.Future<List<Map<String, Object?>>> rawQuery(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i2.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
            returnValueForMissingStub:
                _i2.Future<List<Map<String, Object?>>>.value(
                  <Map<String, Object?>>[],
                ),
          )
          as _i2.Future<List<Map<String, Object?>>>);

  @override
  _i2.Future<_i4.QueryCursor> rawQueryCursor(
    String? sql,
    List<Object?>? arguments, {
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #rawQueryCursor,
              [sql, arguments],
              {#bufferSize: bufferSize},
            ),
            returnValue: _i2.Future<_i4.QueryCursor>.value(
              _FakeQueryCursor_3(
                this,
                Invocation.method(
                  #rawQueryCursor,
                  [sql, arguments],
                  {#bufferSize: bufferSize},
                ),
              ),
            ),
            returnValueForMissingStub: _i2.Future<_i4.QueryCursor>.value(
              _FakeQueryCursor_3(
                this,
                Invocation.method(
                  #rawQueryCursor,
                  [sql, arguments],
                  {#bufferSize: bufferSize},
                ),
              ),
            ),
          )
          as _i2.Future<_i4.QueryCursor>);

  @override
  _i2.Future<_i4.QueryCursor> queryCursor(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryCursor,
              [table],
              {
                #distinct: distinct,
                #columns: columns,
                #where: where,
                #whereArgs: whereArgs,
                #groupBy: groupBy,
                #having: having,
                #orderBy: orderBy,
                #limit: limit,
                #offset: offset,
                #bufferSize: bufferSize,
              },
            ),
            returnValue: _i2.Future<_i4.QueryCursor>.value(
              _FakeQueryCursor_3(
                this,
                Invocation.method(
                  #queryCursor,
                  [table],
                  {
                    #distinct: distinct,
                    #columns: columns,
                    #where: where,
                    #whereArgs: whereArgs,
                    #groupBy: groupBy,
                    #having: having,
                    #orderBy: orderBy,
                    #limit: limit,
                    #offset: offset,
                    #bufferSize: bufferSize,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i2.Future<_i4.QueryCursor>.value(
              _FakeQueryCursor_3(
                this,
                Invocation.method(
                  #queryCursor,
                  [table],
                  {
                    #distinct: distinct,
                    #columns: columns,
                    #where: where,
                    #whereArgs: whereArgs,
                    #groupBy: groupBy,
                    #having: having,
                    #orderBy: orderBy,
                    #limit: limit,
                    #offset: offset,
                    #bufferSize: bufferSize,
                  },
                ),
              ),
            ),
          )
          as _i2.Future<_i4.QueryCursor>);

  @override
  _i2.Future<int> rawUpdate(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i2.Future<int>.value(0),
            returnValueForMissingStub: _i2.Future<int>.value(0),
          )
          as _i2.Future<int>);

  @override
  _i2.Future<int> update(
    String? table,
    Map<String, Object?>? values, {
    String? where,
    List<Object?>? whereArgs,
    _i4.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #update,
              [table, values],
              {
                #where: where,
                #whereArgs: whereArgs,
                #conflictAlgorithm: conflictAlgorithm,
              },
            ),
            returnValue: _i2.Future<int>.value(0),
            returnValueForMissingStub: _i2.Future<int>.value(0),
          )
          as _i2.Future<int>);

  @override
  _i2.Future<int> rawDelete(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i2.Future<int>.value(0),
            returnValueForMissingStub: _i2.Future<int>.value(0),
          )
          as _i2.Future<int>);

  @override
  _i2.Future<int> delete(
    String? table, {
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [table],
              {#where: where, #whereArgs: whereArgs},
            ),
            returnValue: _i2.Future<int>.value(0),
            returnValueForMissingStub: _i2.Future<int>.value(0),
          )
          as _i2.Future<int>);

  @override
  _i4.Batch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeBatch_4(this, Invocation.method(#batch, [])),
            returnValueForMissingStub: _FakeBatch_4(
              this,
              Invocation.method(#batch, []),
            ),
          )
          as _i4.Batch);
}
