// Mocks generated by Mockito 5.4.6 from annotations
// in my_todo_app/test/todo_list_widget_with_mock_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_todo_app/todo.dart' as _i4;
import 'package:my_todo_app/todo_provider.dart' as _i5;
import 'package:rxdart/subjects.dart' as _i3;
import 'package:sqflite_common_ffi/sqflite_ffi.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBehaviorSubject_1<T> extends _i1.SmartFake
    implements _i3.BehaviorSubject<T> {
  _FakeBehaviorSubject_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTodo_2 extends _i1.SmartFake implements _i4.Todo {
  _FakeTodo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodoProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoProvider extends _i1.Mock implements _i5.TodoProvider {
  @override
  _i2.Database get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeDatabase_0(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeDatabase_0(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i2.Database);

  @override
  _i3.BehaviorSubject<List<_i4.Todo>> get todos =>
      (super.noSuchMethod(
            Invocation.getter(#todos),
            returnValue: _FakeBehaviorSubject_1<List<_i4.Todo>>(
              this,
              Invocation.getter(#todos),
            ),
            returnValueForMissingStub: _FakeBehaviorSubject_1<List<_i4.Todo>>(
              this,
              Invocation.getter(#todos),
            ),
          )
          as _i3.BehaviorSubject<List<_i4.Todo>>);

  @override
  set db(_i2.Database? value) => super.noSuchMethod(
    Invocation.setter(#db, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<dynamic> open(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#open, [path]),
            returnValue: _i6.Future<dynamic>.value(),
            returnValueForMissingStub: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> updateList() =>
      (super.noSuchMethod(
            Invocation.method(#updateList, []),
            returnValue: _i6.Future<dynamic>.value(),
            returnValueForMissingStub: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Stream<List<_i4.Todo>> list() =>
      (super.noSuchMethod(
            Invocation.method(#list, []),
            returnValue: _i6.Stream<List<_i4.Todo>>.empty(),
            returnValueForMissingStub: _i6.Stream<List<_i4.Todo>>.empty(),
          )
          as _i6.Stream<List<_i4.Todo>>);

  @override
  _i6.Future<_i4.Todo> insert(_i4.Todo? todo) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [todo]),
            returnValue: _i6.Future<_i4.Todo>.value(
              _FakeTodo_2(this, Invocation.method(#insert, [todo])),
            ),
            returnValueForMissingStub: _i6.Future<_i4.Todo>.value(
              _FakeTodo_2(this, Invocation.method(#insert, [todo])),
            ),
          )
          as _i6.Future<_i4.Todo>);

  @override
  _i6.Future<_i4.Todo> getTodo(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTodo, [id]),
            returnValue: _i6.Future<_i4.Todo>.value(
              _FakeTodo_2(this, Invocation.method(#getTodo, [id])),
            ),
            returnValueForMissingStub: _i6.Future<_i4.Todo>.value(
              _FakeTodo_2(this, Invocation.method(#getTodo, [id])),
            ),
          )
          as _i6.Future<_i4.Todo>);

  @override
  _i6.Future<int> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> update(_i4.Todo? todo) =>
      (super.noSuchMethod(
            Invocation.method(#update, [todo]),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<dynamic> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<dynamic>.value(),
            returnValueForMissingStub: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);
}
